- name: Update Debian
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update RedHat
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Paquetes base
  package:
    name:
      - curl
      - ca-certificates
      - jq
      - gnupg
    state: latest
