- name: Update Debian
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update RedHat
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Paquetes base
  package:
    name: "{{ base_packages }}"
    state: latest

- name: Set timezone
  timezone:
    name: "{{ system_timezone }}"
