---
# Configuración por defecto para el rol Common

# Paquetes base del sistema (Equivalente a tu script original + utilidades modernas)
common_packages:
  - sudo
  - curl
  - wget
  - git
  - jq
  - apache2-utils
  - dialog
  - neofetch
  - htop           # Agregado por buena práctica de monitoreo
  - unzip
  - software-properties-common

# Paquetes relacionados con Python y Entornos Virtuales
python_packages:
  - python3
  - python3-pip
  - python3-venv
  - python3-dev

# Configuración de Git (Opcional, para servidores de desarrollo)
git_config:
  enabled: false
  user_name: "Orion Admin"
  user_email: "admin@oriondesign.com"