---
# Defaults para Docker Moderno

# Usuarios que tendrán permiso para usar Docker sin sudo
docker_users:
  - "{{ ansible_user_id }}"

# Paquetes a eliminar antes de instalar (Limpieza)
docker_old_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc

# Paquetes de la versión moderna (Docker CE + Compose V2)
docker_modern_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# URL de la llave GPG oficial
docker_gpg_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

# Arquitectura para el repositorio
docker_arch: "{{ ansible_architecture | default('amd64') }}"