- name: Prechecks
  hosts: localhost
  gather_facts: true
  tasks:
    - name: SO soportado
      assert:
        that:
          - ansible_os_family in ["Debian", "RedHat"]
        fail_msg: "SO no soportado"

    - name: Arquitectura soportada
      assert:
        that:
          - ansible_architecture in ["x86_64", "amd64"]
