- block:
    - apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  when: ansible_os_family == "Debian"

- get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == "RedHat"

- package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- service:
    name: docker
    enabled: true
    state: started
