---
- name: Remover paquetes Docker conflictivos o antiguos
  ansible.builtin.apt:
    name: [docker, docker-engine, docker.io, containerd, runc]
    state: absent

- name: Instalar dependencias de transporte seguro
  ansible.builtin.apt:
    name: [ca-certificates, curl, gnupg, lsb-release]
    state: present

- name: Crear directorio de llaveros (Keyrings)
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Descargar llave GPG oficial de Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Configurar repositorio estable de Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Instalar Docker Engine + Compose Plugin (Última Versión)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin # Reemplaza al antiguo docker-compose de Python
    state: latest
    update_cache: yes
  notify: Reiniciar Docker

- name: Añadir usuarios al grupo docker
  ansible.builtin.user:
    name: "{{ ansible_user_id }}" # Añade al usuario que ejecuta el script
    groups: docker
    append: yes